services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      # Not removed after integration with ngnix to enable Swagger documnetation on :8000/docs
      - 8000:8000
    env_file:
      - ./backend/.env.docker

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env.docker

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  postgres-data: