"""15_remove order foreign key from transaction models

Revision ID: 096d7b169733
Revises: 4b1ec83ccc20
Create Date: 2025-08-18 15:41:56.878564

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "096d7b169733"
down_revision: Union[str, Sequence[str], None] = "4b1ec83ccc20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("transactions_order_id_fkey"), "transactions", type_="foreignkey"
    )
    op.drop_column("transactions", "order_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("order_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("transactions_order_id_fkey"),
        "transactions",
        "orders",
        ["order_id"],
        ["id"],
    )
    # ### end Alembic commands ###
