"""Add stripe_session_id to users again

Revision ID: 21afddc30399
Revises: ba8d45b0c5e8
Create Date: 2025-08-15 12:32:43.900942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21afddc30399'
down_revision: Union[str, Sequence[str], None] = 'ba8d45b0c5e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_column('transactions', 'updated_at')
    op.add_column('users', sa.Column('stripe_session_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['stripe_session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'stripe_session_id')
    op.add_column('transactions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.alter_column('transactions', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
