"""add original book price to borrow order book

Revision ID: 221ac252d29d
Revises: 3e9212128921
Create Date: 2025-08-06 11:51:30.329504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '221ac252d29d'
down_revision: Union[str, Sequence[str], None] = '3e9212128921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_order_books', sa.Column('original_book_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.create_index('ix_order_id_user_id', 'orders', ['id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_id_user_id', table_name='orders')
    op.drop_column('borrow_order_books', 'original_book_price')
    # ### end Alembic commands ###
