"""14_allow nullable address and phone number in return order

Revision ID: 4b1ec83ccc20
Revises: 53657b397157
Create Date: 2025-08-17 21:40:46.683371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b1ec83ccc20'
down_revision: Union[str, Sequence[str], None] = '53657b397157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('return_orders', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('return_orders', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('return_orders', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('return_orders', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
