"""13_edit address and phone_number to take nullable values

Revision ID: 53657b397157
Revises: 984d233361a6
Create Date: 2025-08-16 20:09:36.682356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53657b397157'
down_revision: Union[str, Sequence[str], None] = '984d233361a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
