"""16_user_tracker_model

Revision ID: 595a36fe14f3
Revises: 096d7b169733
Create Date: 2025-08-23 07:54:05.138243

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "595a36fe14f3"
down_revision: Union[str, Sequence[str], None] = "096d7b169733"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_tracker",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=25), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_user_tracker_user_id", "user_tracker", ["user_id"], unique=False
    )
    op.create_index(
        "ix_user_tracker_user_id_book_id",
        "user_tracker",
        ["user_id", "book_id"],
        unique=False,
    )
    op.add_column(
        "books", sa.Column("rate", sa.Numeric(precision=2, scale=1), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "rate")
    op.drop_index("ix_user_tracker_user_id_book_id", table_name="user_tracker")
    op.drop_index("ix_user_tracker_user_id", table_name="user_tracker")
    op.drop_table("user_tracker")
    # ### end Alembic commands ###
