"""adjust borrow_order_book and purchase_order_book monetary columns, add delivery_fees to orders ,add current_borrowed_books to user, add min_borrowing_fees, increase limit of numbers, add index to user_id in cart and add publish year to book

Revision ID: 8b91812d04b0
Revises: a31fceebc8ca
Create Date: 2025-08-05 21:48:49.790403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b91812d04b0'
down_revision: Union[str, Sequence[str], None] = 'a31fceebc8ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.add_column('books', sa.Column('publish_year', sa.Integer(), nullable=False))
    op.alter_column('books', 'price',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.add_column('borrow_order_books', sa.Column('borrowing_weeks', sa.Integer(), nullable=False))
    op.add_column('borrow_order_books', sa.Column('promo_code_discount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('borrow_order_books', 'deposit_fees',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('borrow_order_books', 'borrow_fees',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('borrow_order_books', 'delay_fees_per_day',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('borrow_order_books', 'borrowing_days')
    op.create_index('ix_user_id', 'carts', ['user_id'], unique=False)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.add_column('orders', sa.Column('delivery_fees', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('purchase_order_books', sa.Column('paid_price_per_book', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('purchase_order_books', sa.Column('promo_code_discount_per_book', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('purchase_order_books', 'price')
    op.add_column('return_orders', sa.Column('delivery_fees', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('settings', sa.Column('min_borrow_fee', sa.Numeric(precision=6, scale=2), nullable=False))
    op.alter_column('settings', 'delivery_fees',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=False)
    op.add_column('users', sa.Column('current_borrowed_books', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_borrowed_books')
    op.alter_column('settings', 'delivery_fees',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=False)
    op.drop_column('settings', 'min_borrow_fee')
    op.drop_column('return_orders', 'delivery_fees')
    op.add_column('purchase_order_books', sa.Column('price', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=False))
    op.drop_column('purchase_order_books', 'promo_code_discount_per_book')
    op.drop_column('purchase_order_books', 'paid_price_per_book')
    op.drop_column('orders', 'delivery_fees')
    op.alter_column('categories', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    op.drop_index('ix_user_id', table_name='carts')
    op.add_column('borrow_order_books', sa.Column('borrowing_days', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('borrow_order_books', 'delay_fees_per_day',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('borrow_order_books', 'borrow_fees',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('borrow_order_books', 'deposit_fees',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.drop_column('borrow_order_books', 'promo_code_discount')
    op.drop_column('borrow_order_books', 'borrowing_weeks')
    op.alter_column('books', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=False)
    op.drop_column('books', 'publish_year')
    op.alter_column('authors', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
