"""add stripe session id to user

Revision ID: a0ac17a377aa
Revises: e78728d40358
Create Date: 2025-08-12 19:34:50.035654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ac17a377aa'
down_revision: Union[str, Sequence[str], None] = 'e78728d40358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'cover_img',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_user_id'), table_name='carts')
    op.create_index('ix_cart_id', 'carts', ['id', 'user_id'], unique=False)
    op.add_column('users', sa.Column('stripe_session_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['stripe_session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'stripe_session_id')
    op.drop_index('ix_cart_id', table_name='carts')
    op.create_index(op.f('ix_user_id'), 'carts', ['user_id'], unique=False)
    op.alter_column('books', 'cover_img',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
