"""17_change rate to rating

Revision ID: b1d26ec441d8
Revises: 595a36fe14f3
Create Date: 2025-08-23 09:51:30.389330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1d26ec441d8'
down_revision: Union[str, Sequence[str], None] = '595a36fe14f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=False))
    op.drop_column('books', 'rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('rate', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=False))
    op.drop_column('books', 'rating')
    # ### end Alembic commands ###
