"""adjust return_date in borrow order book

Revision ID: ba8d45b0c5e8
Revises: a0ac17a377aa
Create Date: 2025-08-14 07:45:10.506778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba8d45b0c5e8'
down_revision: Union[str, Sequence[str], None] = 'a0ac17a377aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_order_books', sa.Column('actual_return_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('borrow_order_books', sa.Column('expected_return_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('borrow_order_books', 'return_date')
    op.alter_column('orders', 'pick_up_type', nullable=False, new_column_name='pickup_type')
    op.alter_column('orders', 'pick_up_date', nullable=True, new_column_name='pickup_date')
    op.alter_column('return_orders', 'pick_up_type', nullable=False, new_column_name='pickup_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_order_books', sa.Column('return_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('borrow_order_books', 'expected_return_date')
    op.drop_column('borrow_order_books', 'actual_return_date')
    op.alter_column('orders', 'pickup_type', nullable=False, new_column_name='pick_up_type')
    op.alter_column('orders', 'pickup_date', nullable=True, new_column_name='pick_up_date')
    op.alter_column('return_orders', 'pickup_type', nullable=False, new_column_name='pick_up_type')
    # ### end Alembic commands ###
