"""add courier_id on the order model

Revision ID: e78728d40358
Revises: f94566580ae1
Create Date: 2025-08-09 10:26:38.568923

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e78728d40358"
down_revision: Union[str, Sequence[str], None] = "f94566580ae1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "authors",
        "name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_authors_id"), table_name="authors")
    op.create_unique_constraint(None, "authors", ["name"])
    op.alter_column(
        "categories",
        "name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.create_unique_constraint(None, "categories", ["name"])
    op.add_column("orders", sa.Column("courier_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "orders", "users", ["courier_id"], ["id"])
    op.alter_column(
        "return_orders", "courier_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "return_orders", "courier_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "courier_id")
    op.drop_constraint(None, "categories", type_="unique")
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    op.alter_column(
        "categories",
        "name",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_constraint(None, "authors", type_="unique")
    op.create_index(op.f("ix_authors_id"), "authors", ["id"], unique=False)
    op.alter_column(
        "authors",
        "name",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
