"""18_update notifications schema

Revision ID: ee24dddc0fdf
Revises: b1d26ec441d8
Create Date: 2025-09-05 15:17:43.408931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee24dddc0fdf'
down_revision: Union[str, Sequence[str], None] = 'b1d26ec441d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('notifications_order_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_promo_code_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_return_order_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'order_id')
    op.drop_column('notifications', 'promo_code_id')
    op.drop_column('notifications', 'status')
    op.drop_column('notifications', 'return_order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('return_order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('status', postgresql.ENUM('READ', 'UNREAD', name='notificationstatus'), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('promo_code_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('notifications_return_order_id_fkey'), 'notifications', 'return_orders', ['return_order_id'], ['id'])
    op.create_foreign_key(op.f('notifications_promo_code_id_fkey'), 'notifications', 'promo_codes', ['promo_code_id'], ['id'])
    op.create_foreign_key(op.f('notifications_order_id_fkey'), 'notifications', 'orders', ['order_id'], ['id'])
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'data')
    # ### end Alembic commands ###
