"""edit cart model

Revision ID: f94566580ae1
Revises: 221ac252d29d
Create Date: 2025-08-08 15:06:33.692487

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f94566580ae1"
down_revision: Union[str, Sequence[str], None] = "221ac252d29d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("carts", sa.Column("borrowing_weeks", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("carts", "borrowing_weeks")
    # ### end Alembic commands ###
